spring:
  profiles:
    active: local
  datasource:
    url:  jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: Dmitry
    password: Sport-life--h2
  h2:
    console:
      enabled: true
      path: /h2-console
